### ISSUE TITLE
ERROR (undefined_table): relation "posts" does not exist

### ISSUE THREAD

**Issue by CharlyMTO** [jcieslar/blog_phoenix#3]
- Install dependencies with mix deps.get
- Create and update your database mix ecto.create && mix.ecto.migrate
- Start Phoenix endpoint with mix phoenix.server

run localhost:4000
ERROR (undefined_table): relation "posts" does not exist

**Comment by CharlyMTO** [comment]
Lol
bad mix.ecto.migrate
good mix ecto.migrate

**Comment by jcieslar** [comment]
;]
